In [4]:
# Exercise 1
import numpy as np

array = np.arange(1, 11)
reshaped_array = array.reshape(2, 5)
print(reshaped_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
# Exercise 2
import numpy as np

array = np.arange(1, 21)
extracted_elements = array[5:15]
print(extracted_elements)

[ 6  7  8  9 10 11 12 13 14 15]


In [12]:
# Exercise 3
import pandas as pd

data = {'apples': 3, 'bananas': 2, 'oranges': 1}
series = pd.Series(data)
series['pears'] = 4
print(series)

apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [14]:
# Exercise 4
import pandas as pd

# Create a dictionary with the data
data = {
    'name': ['Arya', 'Binoy', 'Charlie', 'David', 'Edna', 'Franklin', 'Grace', 'Hanna', 'Isaac', 'Jack'],
    'age': [24, 30, 22, 35, 29, 31, 26, 27, 32, 28],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male']
}
df = pd.DataFrame(data)
print(df)

       name  age  gender
0      Arya   24  Female
1     Binoy   30    Male
2   Charlie   22    Male
3     David   35    Male
4      Edna   29  Female
5  Franklin   31    Male
6     Grace   26  Female
7     Hanna   27  Female
8     Isaac   32    Male
9      Jack   28    Male


In [20]:
# Exercise 5
import pandas as pd
data = {
    'name': ['Arya', 'Binoy', 'Charlie', 'David', 'Edna', 'Franklin', 'Grace', 'Hanna', 'Isaac', 'Jack'],
    'age': [24, 30, 22, 35, 29, 31, 26, 27, 32, 28],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male']
}
df = pd.DataFrame(data)
df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Manager', 'Programmer',
                    'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print(df)

       name  age  gender  occupation
0      Arya   24  Female  Programmer
1     Binoy   30    Male     Manager
2   Charlie   22    Male     Analyst
3     David   35    Male     Manager
4      Edna   29  Female  Programmer
5  Franklin   31    Male     Analyst
6     Grace   26  Female  Programmer
7     Hanna   27  Female     Manager
8     Isaac   32    Male     Analyst
9      Jack   28    Male  Programmer


In [18]:
# Exercise 5
import pandas as pd

data = {
    'name': ['Arya', 'Binoy', 'Charlie', 'David', 'Edna', 'Franklin', 'Grace', 'Hanna', 'Isaac', 'Jack'],
    'age': [24, 30, 22, 35, 29, 31, 26, 27, 32, 28],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male'],
    'occupation': ['Programmer', 'Manager', 'Analyst', 'Manager', 'Programmer',
                   'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
}
df = pd.DataFrame(data)
filtered_df = df[df['age'] >= 30]
print(filtered_df)

    name  age gender occupation
1    Bob   30   Male    Manager
3  David   35   Male    Manager
5  Frank   31   Male    Analyst
8  Isaac   32   Male    Analyst


In [22]:
# Exercise 6
import pandas as pd

data = {
    'name': ['Arya', 'Binoy', 'Charlie', 'David', 'Edna', 'Franklin', 'Grace', 'Hanna', 'Isaac', 'Jack'],
    'age': [24, 30, 22, 35, 29, 31, 26, 27, 32, 28],
    'gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male'],
    'occupation': ['Programmer', 'Manager', 'Analyst', 'Manager', 'Programmer',
                   'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
}
df = pd.DataFrame(data)
csv_file_path = 'people_data.csv'  
df.to_csv(csv_file_path, index=False) 
loaded_df = pd.read_csv(csv_file_path)
print(loaded_df)

      name  age  gender  occupation
0    Alice   24  Female  Programmer
1      Bob   30    Male     Manager
2  Charlie   22    Male     Analyst
3    David   35    Male     Manager
4      Eva   29  Female  Programmer
5    Frank   31    Male     Analyst
6    Grace   26  Female  Programmer
7   Hannah   27  Female     Manager
8    Isaac   32    Male     Analyst
9     Jack   28    Male  Programmer
